

```{r get enrollment by cycle}
#| echo: false
#| eval: !expr params$enrollment_by_cycle
#| results: asis

atriReporter:::format_quarto("Enrollment by Year", "subsection")

atri_registry <- atriReporter::get_registry(examdate, apply_labels = TRUE)

atri_registry$event_label <- gsub(
  " - Month [0-9]{1,2}",
  "",
  atri_registry$event_label
)

enrollment_tbl <- atri_registry %>%
  dplyr::mutate(
    Year = format(as.Date(examdate), "%Y"),
    Year = ifelse(is.na(Year), "Unknown Date", Year)
  ) %>%
  dplyr::group_by(Year) %>%
  dplyr::count(event_label) %>%
  tidyr::pivot_wider(
    names_from = event_label,
    values_from = n,
    values_fill = 0
  )

data.frame(
  Year = "Total",
  Cycle = unique(atri_registry$event_label),
  Value = colSums(enrollment_tbl[2:5])
) %>%
  tidyr::pivot_wider(names_from = Cycle, values_from = Value) %>%
  rbind(enrollment_tbl, .) %>%
  flextable::flextable() %>%
  atriReporter:::ft_add_abcds_theme() %>%
  flextable::width(j = 1, width = 1.25) %>%
  flextable::width(j = 2:5, width = 1)

atriReporter:::format_quarto(type = "newpage")

```



```{r retreiving demographics from atri and loni}
#| echo: false
#| eval: !expr (params$demographics) | (params$enrollment_by_cycle)
#| results: asis

demographic_variables <- c(
  "age_at_visit",
  "de_race",
  "de_gender",
  "de_ethnicity"
)

atri_demographics <-
  atriReporter::get_demographics(
    !!!demographic_variables,
    site = NULL,
    cycle = NULL,
    apply_labels = TRUE
  )

if (!is.null(params$lonidir)) {
  loni_demographics <- abcds::read_demographics(
    params$lonidir,
    person = "participants",
    simplify = TRUE
  )

  loni_demographics <- abcds::apply_factor_labels(loni_demographics)

  atri_demographics <- atriReporter:::loni_join(
    atri_data = atri_demographics,
    loni_data = loni_demographics,
    variables = demographic_variables
  )
}

```


```{r retreiving demographics from atri}
#| echo: false
#| eval: !expr params$demographics
#| results: asis

atriReporter:::format_quarto("Demographics", "subsection")

if ("u01_event_code" %in% names(atri_demographics)) {
  baseline_demographics <- atri_demographics %>%
    dplyr::filter(
      (is.na(u01_event_code) & u19_event_code == "cyc1") |
        (is.na(u19_event_code) & u01_event_code == "bl")
    ) %>%
    dplyr::arrange(ids, event_code) %>%
    dplyr::group_by(ids) %>%
    dplyr::summarise(dplyr::across(dplyr::everything(), dplyr::first))
} else {
  baseline_demographics <- atri_demographics %>%
    dplyr::filter(event_code == "cyc1")
}


baseline_demographics %>%
  dplyr::mutate(de_race = "") %>%
  dplyr::select(
    age_at_visit,
    de_gender,
    de_ethnicity,
    de_race,
    White:`Native Hawaiian/Other Pacific Islander`
  ) %>%
  dplyr::select(dplyr::where(~ !(all(. %in% c(0, NA))))) %>%
  dplyr::mutate(dplyr::across(dplyr::where(is.factor), forcats::fct_drop)) %>%
  gtsummary::tbl_summary(
    missing = "no",
    label = list(
      age_at_visit ~ "Age (Years)",
      de_gender ~ "Gender",
      de_ethnicity ~ "Ethnicity: Hispanic/Latino?",
      de_race ~ "Race"
    ),
    statistic = list(gtsummary::all_continuous() ~ "{mean} ± {sd}"),
    digits = list(gtsummary::all_continuous() ~ 1),
  ) %>%
  gtsummary::as_tibble() %>%
  dplyr::filter(.[[1]] != "") %>%
  flextable::flextable() %>%
  flextable::set_header_labels(
    values = c("Variable", paste0("N = ", nrow(baseline_demographics)))
  ) %>%
  atriReporter:::ft_add_abcds_theme() %>%
  flextable::bold(i = c(1:2, 5:6), j = 1) %>%
  flextable::width(j = 1, width = 4) %>%
  flextable::width(j = 2, width = 1.5)


atriReporter:::format_quarto(type = "newpage")

```


