```{r getting imaging metadata from atri and loni for completed scans}
#| echo: false
#| eval: !expr (params$imaging_scan_counts) | (params$imaging_scan_counts_controls)
#| results: asis

atriReporter:::format_quarto("Imaging Type by Number of Scans", "subsection")

count_imaging <- function(
  controls = FALSE,
  lonidir = NULL
) {
  atri_imaging <-
    purrr::map(
      atriReporter:::.imaging_key[["atri_scan_names"]],
      .f = function(x) {
        img <- atriReporter::get_imaging(
          done,
          imaging = x,
          controls = controls
        )
        img$done <- as.numeric(img$done)
        doneindx <- which(colnames(img) == "done")
        colnames(img)[doneindx] <- paste0(gsub("meta", "", x), "_done")
        return(img)
      }
    )

  id_vars <- atriReporter:::get_ids(atri_imaging[[1]])
  atri_imaging <- purrr::reduce(atri_imaging, dplyr::full_join, by = id_vars)
  atri_imaging$ids <- atri_imaging$subject_label

  if (controls) {
    person <- "controls"
  } else {
    person <- "participants"
  }

  if (!is.null(lonidir)) {
    loni_imaging <- purrr::map(
      atriReporter:::.imaging_key[["loni_scan_names"]],
      .f = function(x) {
        img <- abcds::read_imaging(person = person, scan = x)
        img <- img[, c("subject_label", "event_sequence", paste0(x, "_done"))]
        return(img)
      }
    )

    loni_imaging <- purrr::reduce(
      loni_imaging,
      dplyr::full_join,
      by = c("subject_label", "event_sequence")
    )

    atri_imaging <- atriReporter:::loni_join(
      atri_data = atri_imaging,
      loni_data = loni_imaging,
      variables = paste0(
        atriReporter:::.imaging_key[["loni_scan_names"]],
        "_done"
      )
    )
  }

  imaging_scan_counts <- atriReporter::multiple_count_by(
    data = atri_imaging,
    names = paste0(atriReporter:::.imaging_key[["loni_scan_names"]], "_done"),
    labels = atriReporter:::.imaging_key[["scan_labels"]],
    ids = "ids",
    varname = "Imaging Scan"
  )

  person <- paste0(
    toupper(substr(person, 1, 1)),
    tolower(substr(person, 2, nchar(person)))
  )

  if (person == "Controls") {
    person <- "Sibling Controls"
  }

  return(dplyr::bind_cols(Person = person, imaging_scan_counts))
}

if (params$imaging_scan_counts & params$imaging_scan_counts_controls) {
  imaging_scan_counts <- count_imaging(
    lonidir = params$lonidir
  ) %>%
    dplyr::bind_rows(count_imaging(
      controls = TRUE,
      lonidir = Sys.getenv("ABCDS_LONI_DATA_DIRECTORY")
    ))
} else if (params$imaging_scan_counts & !params$imaging_scan_counts_controls) {
  imaging_scan_counts <- count_imaging(
    lonidir = params$lonidir
  )
} else if (!params$imaging_scan_counts & params$imaging_scan_counts_controls) {
  imaging_scan_counts <- count_imaging(
    controls = TRUE,
    lonidir = params$lonidir
  )
}

imgtime <- as.numeric(colnames(imaging_scan_counts)[
  3:ncol(imaging_scan_counts)
])

imaging_scan_counts_footnote <- paste(
  glue::glue("Numbers {min(imgtime)} to {max(imgtime)}"),
  "show how many participants completed at least that many scans."
)

imaging_scan_counts %>%
  flextable::as_grouped_data(groups = "Person") %>%
  flextable::as_flextable(hide_grouplabel = TRUE) %>%
  atriReporter:::ft_add_abcds_theme(grouped_column = TRUE) %>%
  flextable::add_footer_row(
    values = imaging_scan_counts_footnote,
    colwidths = (max(imgtime) + 1)
  ) %>%
  flextable::width(j = 1, width = 2) %>%
  flextable::width(j = 2:(max(imgtime) + 1), width = 3.25 / max(imgtime)) %>%
  flextable::bold(i = ~ !is.na(Person))

atriReporter:::format_quarto(type = "newpage")


```


```{r getting mri sequence data from atri and loni for completed scans}
#| echo: false
#| eval: !expr (params$mri_sequence_counts) | (params$mri_sequence_counts_controls)
#| results: asis

atriReporter:::format_quarto("MRI Sequences by Number of Scans", "subsection")

# params <- list()
# params$lonidir <- "/Users/bhelsel/Desktop/Data/ABCDS LONI DATA"
# lonidir = params$lonidir
# controls = TRUE

count_mri_sequencing <- function(controls = FALSE, lonidir = NULL) {
  atri_mri_imaging <- atriReporter::get_mri_sequences(
    name = "description",
    controls = controls,
    apply_labels = TRUE
  )

  atri_mri_imaging$ids <- atri_mri_imaging$subject_label

  if (controls) {
    person <- "controls"
  } else {
    person <- "participants"
  }

  if (!is.null(lonidir)) {
    loni_mri_imaging <- abcds::read_imaging(
      lonidir,
      person = person,
      scan = "mri"
    )

    loni_mri_imaging <- loni_mri_imaging[, c(
      "subject_label",
      "event_sequence",
      "mri_done",
      "mrseqs"
    )]

    loni_mri_imaging <- abcds::apply_factor_labels(loni_mri_imaging)

    mri_columns <- c(
      "mri_done",
      "mrseqs",
      atriReporter:::.mri_sequence_key[["description"]]
    )

    atri_mri_imaging <- atriReporter:::loni_join(
      atri_data = atri_mri_imaging,
      loni_data = loni_mri_imaging,
      variables = mri_columns
    ) %>%
      dplyr::arrange(ids, event_code, event_sequence) %>%
      dplyr::group_by(ids, event_code) %>%
      dplyr::filter(!duplicated(u19_bds_id, event_code))
  }

  mri_sequences <- atriReporter::multiple_count_by(
    data = atri_mri_imaging,
    names = atriReporter:::.mri_sequence_key[["description"]],
    labels = atriReporter:::.mri_sequence_key[["abbreviation"]],
    ids = "ids",
    varname = "MRI Sequence"
  )

  person <- paste0(
    toupper(substr(person, 1, 1)),
    tolower(substr(person, 2, nchar(person)))
  )

  if (person == "Controls") {
    person <- "Sibling Controls"
  }

  return(dplyr::bind_cols(Person = person, mri_sequences))
}

if (params$mri_sequence_counts & params$mri_sequence_counts_controls) {
  mri_sequence_counts <- count_mri_sequencing(
    lonidir = params$lonidir
  ) %>%
    dplyr::bind_rows(count_mri_sequencing(
      controls = TRUE,
      lonidir = Sys.getenv("ABCDS_LONI_DATA_DIRECTORY")
    ))
} else if (params$mri_sequence_counts & !params$mri_sequence_counts_controls) {
  mri_sequence_counts <- count_mri_sequencing(
    lonidir = params$lonidir
  )
} else if (!params$mri_sequence_counts & params$mri_sequence_counts_controls) {
  mri_sequence_counts <- count_mri_sequencing(
    controls = TRUE,
    lonidir = params$lonidir
  )
}

mritime <- as.numeric(colnames(mri_sequence_counts)[
  3:ncol(mri_sequence_counts)
])

mri_sequences_counts_footnote <- paste(
  glue::glue("Numbers {min(mritime)} to {max(mritime)}"),
  "show how many participants completed at least that many sequences."
)

mri_sequence_counts %>%
  flextable::as_grouped_data(groups = "Person") %>%
  flextable::as_flextable(hide_grouplabel = TRUE) %>%
  atriReporter:::ft_add_abcds_theme(grouped_column = TRUE) %>%
  flextable::add_footer_row(
    values = mri_sequences_counts_footnote,
    colwidths = (max(mritime) + 1)
  ) %>%
  flextable::width(j = 1, width = 2) %>%
  flextable::width(j = 2:(max(mritime) + 1), width = 3 / max(mritime)) %>%
  flextable::bold(i = ~ !is.na(Person))

atriReporter:::format_quarto(type = "newpage")

```



```{r  displaying table for imaging scans by site}
#| echo: false
#| eval: !expr params$imaging_scan_counts_by_site
#| results: asis

atriReporter:::format_quarto("Amyloid PET Scans by Site", "subsection")

atri_imaging <-
  purrr::map(imaging_map[["atri_scan_names"]], .f = function(x) {
    img <- atriReporter::get_imaging(done, imaging = x)
    img$done <- as.numeric(img$done)
    doneindx <- which(colnames(img) == "done")
    colnames(img)[doneindx] <- paste0(gsub("meta", "", x), "_done")
    return(img)
  })

id_vars <- atriReporter:::get_ids(atri_imaging[[1]])
atri_imaging <- purrr::reduce(atri_imaging, dplyr::full_join, by = id_vars)
atri_imaging$ids <- atri_imaging$subject_label


atri_imaging %>%
  dplyr::count(Site = site_label, event_code, done = amy_done) %>%
  dplyr::filter(done == 1) %>%
  dplyr::mutate(
    event_code = factor(
      event_code,
      levels = c("cyc1", "cyc2", "cyc3"),
      labels = c("Cycle 1\n", "Cycle 2\n", "Cycle 3\n")
    )
  ) %>%
  tidyr::pivot_wider(
    id_cols = Site,
    names_from = event_code,
    values_from = n,
    values_fill = 0
  ) %>%
  dplyr::arrange(Site) %>%
  flextable::flextable() %>%
  atriReporter:::ft_add_abcds_theme() %>%
  flextable::width(j = 1, width = 3) %>%
  flextable::width(j = 2:4, width = 2.25 / 3)

atriReporter:::format_quarto(type = "newpage")

```


```{r}

# lonidir <- '/Users/bhelsel/Desktop/Data/ABCDS LONI DATA'

# list.files(lonidir, "MRI", full.names = TRUE)
# loni_mri <- grepl()

# mri <- get_imaging(done, mrseqs, apply_labels = TRUE, imaging = "mrimeta")

# get_codebook(abcds, mrimeta)

```