
```{r get karyotype data from atri}
#| echo: false
#| eval: !expr any(grepl("karyotype", names(params)))
#| results: asis

karyotype <- atriReporter::get_karyotype(
  karyotype,
  apply_labels = TRUE
)

```

```{r add karyotype flextable}
#| echo: false
#| eval: !expr params$karyotype
#| results: asis

atriReporter:::format_quarto("Karyotype", "subsection")

karyotype %>%
  dplyr::count(karyotype) %>%
  dplyr::filter(!is.na(karyotype) & karyotype != "Other") %>%
  tidyr::pivot_wider(
    names_from = karyotype,
    values_from = n,
    values_fill = 0
  ) %>%
  flextable::flextable() %>%
  atriReporter:::ft_add_abcds_theme() %>%
  flextable::width(width = 5.25 / 3)

atriReporter:::format_quarto(type = "newpage")

```

```{r add karyotype by site flextable}
#| echo: false
#| eval: !expr params$karyotype_by_site
#| results: asis

atriReporter:::format_quarto("Karyotype by Site", "subsection")

karyotype %>%
  dplyr::group_by(Site = site_label) %>%
  dplyr::count(karyotype) %>%
  dplyr::filter(!is.na(karyotype) & karyotype != "Other") %>%
  tidyr::pivot_wider(
    names_from = karyotype,
    values_from = n,
    values_fill = 0
  ) %>%
  flextable::flextable() %>%
  atriReporter:::ft_add_abcds_theme() %>%
  flextable::width(j = 1, width = 2.25) %>%
  flextable::width(j = 2:4, width = 1)

atriReporter:::format_quarto(type = "newpage")

```